server:
  port: 8400
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: icq-service
  redis:
    host: 112.126.84.2
    port: 6379
    jedis:
      pool:
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      url: jdbc:mysql://112.126.84.2/pet_zoology?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kykj1234.
mybatis:
  configuration:
    map-underscore-to-camel-case: true

icq:
  distance: 500

mapper:
  wrap-keyword: "`{0}`"

logging:
  level:
    com.kaiyu.mapper: debug

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 6000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1  #当前服务的IP地址
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:@project.version@
