server:
  port: 8089
  tomcat:
    max-swallow-size: 150MB
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 150MB
  security:
    user:
      name: "admin"
      password: "kykj1234"
  redis:
    host: 39.105.153.98
    port: 6379
    jedis:
      pool:
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      url: jdbc:mysql://112.126.84.2/pet_zoology?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kykj1234.
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mapper:
  wrap-keyword: "`{0}`"
